all : TCPEchoClient4 TCPEchoServer4

TCPEchoClient4 : TCPEchoClient4.c
	gcc -O3 -Wall -o TCPEchoClient4 TCPEchoClient4.c

TCPEchoServer4 : TCPEchoServer4.c
	gcc -O3 -Wall -o TCPEchoServer4 TCPEchoServer4.c

clean :
	rm -rf TCPEchoClient4 TCPEchoServer4 -rf
